# run.ps1 -- [2] OPERATION / run the agent. No admin needed (Auto-start on boot,
# when added, will self-elevate). Run standalone:
#   powershell -ExecutionPolicy Bypass -File .\run.ps1
#
# Core is built (Status, Service Control, Restart, Sessions list/compact, list
# skills/MCPs, Dashboard). Deferred bits are marked TODO (see tmp-menu.md).

if (-not (Get-Command Say -ErrorAction SilentlyContinue)) { . "$PSScriptRoot\common.ps1" }

# --- status ------------------------------------------------------------------
function Row ($label, $on) {
    $tag = if ($on) { 'yes' } else { 'no' }
    $col = if ($on) { 'Green' } else { 'DarkGray' }
    Write-Host ("   {0,-16} " -f $label) -NoNewline
    Write-Host $tag -ForegroundColor $col
}
function Show-Status {
    Clear-Host
    Say "== STATUS ==" Cyan
    Write-Host ""
    Row "OpenClaw"   (Test-OpenClaw)
    Row "configured" (Test-Configured)
    Row "gateway up" (Test-GatewayUp)
    if ($UseOllama) {
        Row "Ollama"     (Test-Ollama)
        Row "ollama up"  (Test-OllamaUp)
        Row "$Model"     ([bool]((ollama list 2>$null | Out-String) -match [regex]::Escape($Model)))
    }
    if ($UseAndroid) {
        Row "AVD created" (Test-Avd)
        Row "device up"   (Test-DeviceUp)
    }
    Pause
}

# --- services ----------------------------------------------------------------
function Start-Ollama {
    if (Test-OllamaUp) { Ok "Ollama already up."; return }
    Start-Process ollama -ArgumentList 'serve' -WindowStyle Hidden
    foreach ($i in 1..15) { if (Test-OllamaUp) { break }; Start-Sleep 1 }
    if (Test-OllamaUp) { Ok "Ollama started." } else { Warn "Ollama did not come up." }
}
function Stop-Ollama    { Get-Process ollama* -ErrorAction SilentlyContinue | Stop-Process -Force; Ok "Ollama stopped." }
function Restart-Ollama { Stop-Ollama; Start-Sleep 1; Start-Ollama }

function Start-Gateway   { $ErrorActionPreference='Continue'; openclaw gateway start   *>$null; $ErrorActionPreference='Stop'; Ok "gateway start issued." }
function Stop-Gateway    { $ErrorActionPreference='Continue'; openclaw gateway stop    *>$null; $ErrorActionPreference='Stop'; Ok "gateway stopped." }
function Restart-Gateway {
    Say ">>> Restarting the OpenClaw gateway..." Cyan
    $ErrorActionPreference='Continue'; openclaw gateway restart *>$null
    foreach ($i in 1..10) { if (Test-GatewayUp) { break }; Start-Sleep 2 }
    $ErrorActionPreference='Stop'
    if (Test-GatewayUp) { Ok "gateway is back up." } else { Warn "gateway did not come up in time." }
    Pause
}

# --- auto-start on boot (THE permanent fix for "connection refused") ----------
# The gateway can come up after a reboot while Ollama's daemon does NOT -- then
# the provider endpoint (:11434) is dead and every agent turn fails. This logon
# Scheduled Task brings Ollama up, WAITS for it, then restarts the gateway, so
# the provider is always live before the agent runs. Needs admin (task register).
$AutoTask = 'OpenClaw Autostart'
function Test-AutoStart { [bool](Get-ScheduledTask -TaskName $AutoTask -ErrorAction SilentlyContinue) }

function Enable-AutoStart {
    if (-not (Ensure-Admin)) { return }
    Say ">>> Enabling auto-start on boot (Ollama, then gateway)..." Cyan
    $script = "$ClawDir\oc-autostart.ps1"
    $body = @'
# Auto-generated by run.ps1. Brings the LLM provider up before the gateway.
Start-Process ollama -ArgumentList 'serve' -WindowStyle Hidden
foreach ($i in 1..30) { try { Invoke-RestMethod 'http://127.0.0.1:11434/api/tags' -TimeoutSec 2 > $null; break } catch { Start-Sleep 2 } }
openclaw gateway restart
'@
    New-Item -ItemType Directory -Force $ClawDir | Out-Null
    [IO.File]::WriteAllText($script, $body, (New-Object Text.UTF8Encoding($false)))
    $action  = New-ScheduledTaskAction -Execute 'powershell.exe' -Argument "-NoProfile -WindowStyle Hidden -ExecutionPolicy Bypass -File `"$script`""
    $trigger = New-ScheduledTaskTrigger -AtLogOn
    $set     = New-ScheduledTaskSettingsSet -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries -StartWhenAvailable
    Register-ScheduledTask -TaskName $AutoTask -Action $action -Trigger $trigger -Settings $set -RunLevel Highest -Force | Out-Null
    Ok "auto-start enabled -- Ollama + gateway come up at every logon."
    Pause
}

function Disable-AutoStart {
    if (-not (Ensure-Admin)) { return }
    Unregister-ScheduledTask -TaskName $AutoTask -Confirm:$false -ErrorAction SilentlyContinue
    Ok "auto-start disabled."
    Pause
}

function Menu-Service {
    while ($true) {
        Clear-Host
        Say "== SERVICE CONTROL ==" Cyan
        Row "Ollama"     (Test-OllamaUp)
        Row "gateway"    (Test-GatewayUp)
        Row "auto-start" (Test-AutoStart)
        Write-Host ""
        Line 1 "Start Ollama"      ; Line 2 "Stop Ollama"      ; Line 3 "Restart Ollama"
        Line 4 "Start gateway"     ; Line 5 "Stop gateway"     ; Line 6 "Restart gateway"
        Line 7 ("Toggle auto-start on boot  (now: {0})" -f $(if (Test-AutoStart) { 'ON' } else { 'off' }))
        Footer
        $c = Read-Choice 7
        if ($null -eq $c) { return }
        switch ($c) {
            '1' { if ($UseOllama) { Start-Ollama } ; Pause }
            '2' { if ($UseOllama) { Stop-Ollama }  ; Pause }
            '3' { if ($UseOllama) { Restart-Ollama } ; Pause }
            '4' { Start-Gateway   ; Pause }
            '5' { Stop-Gateway    ; Pause }
            '6' { Restart-Gateway }
            '7' { if (Test-AutoStart) { Disable-AutoStart } else { Enable-AutoStart } }
        }
    }
}

# --- sessions ----------------------------------------------------------------
$TelegramSession = 'agent:main:telegram'
function Menu-Sessions {
    while ($true) {
        Clear-Host
        Say "== SESSION MANAGEMENT ==" Cyan
        Write-Host ""
        Line 1 "List all sessions"
        Line 2 "Check Telegram context/token status"
        Line 3 "Compact Telegram session ($TelegramSession)"
        Line 4 "Reset Telegram session"
        Footer
        $c = Read-Choice 4
        if ($null -eq $c) { return }
        $ErrorActionPreference = 'Continue'
        switch ($c) {
            '1' { openclaw sessions list; Pause }
            '2' { openclaw sessions list --json 2>$null | Out-String | Write-Host; Pause }
            '3' { openclaw sessions compact --agent main 2>$null; Ok "compact requested."; Pause }
            '4' {
                # TODO(defer): no CLI 'reset' verb -- needs the session-store file
                # layout (delete the agent:main:telegram entry, then gateway restart).
                # Investigate live before wiring. See tmp-menu.md.
                Warn "Reset not wired yet -- needs the session-store layout (see tmp-menu.md)."
                Pause
            }
        }
        $ErrorActionPreference = 'Stop'
    }
}

# --- one-shot operations -----------------------------------------------------
function List-SkillsMcps {
    Clear-Host; $ErrorActionPreference = 'Continue'
    Say "== SKILLS ==" Cyan; openclaw skills list
    Say "`n== MCP servers ==" Cyan; openclaw mcp list
    $ErrorActionPreference = 'Stop'; Pause
}
function Open-Dashboard { $ErrorActionPreference='Continue'; openclaw dashboard; $ErrorActionPreference='Stop'; Ok "dashboard opened."; Pause }

# TODO: recommend the best model for THIS machine's VRAM.
function Recommend-Model {
    # Read MODELS.md (catalog: model, params, quant, layers/kv-heads/head-dim, max
    # context, quality tier) + detect GPU VRAM, then for each model compute the
    # largest context that FITS (weights + KV cache; note q8_0 KV cache = ~half of
    # FP16) and recommend the strongest model that fits with a usable context.
    # Print the pick + the exact setup to apply:
    #   ollama pull <model>
    #   OLLAMA_FLASH_ATTENTION=1 ; OLLAMA_KV_CACHE_TYPE=q8_0
    #   openclaw num_ctx / contextWindow / contextTokens = <fit>
    # (Automates the manual VRAM_TABLE.md + q8_0 + 128k-fit work we did by hand.)
    Clear-Host
    Say "== RECOMMEND MODEL FOR YOUR VRAM ==" Cyan
    Warn "Not wired yet -- see the TODO in this function."
    if (-not (Test-Path (Join-Path $RepoDir 'MODELS.md'))) { Warn "MODELS.md not present in the repo yet." }
    Pause
}

# --- configure openclaw (ongoing config -- moved here from Install) -----------
# WinForms dialogs need an STA thread; PowerShell 7 runs MTA by default, where
# ShowDialog() just HANGS. Run them on a dedicated STA runspace. Return '' on cancel.
function Pick-Folder ($desc) {
    $sb = {
        param($d)
        Add-Type -AssemblyName System.Windows.Forms
        $dlg = New-Object System.Windows.Forms.FolderBrowserDialog; $dlg.Description = $d
        if ($dlg.ShowDialog() -eq [System.Windows.Forms.DialogResult]::OK) { $dlg.SelectedPath } else { '' }
    }
    $rs = [runspacefactory]::CreateRunspace(); $rs.ApartmentState = 'STA'; $rs.Open()
    $p = [powershell]::Create(); $p.Runspace = $rs; [void]$p.AddScript($sb.ToString()).AddArgument($desc)
    $r = $p.Invoke(); $rs.Close(); $p.Dispose(); "$($r | Select-Object -Last 1)"
}
function Pick-File ($title, $filter) {
    $sb = {
        param($t, $f)
        Add-Type -AssemblyName System.Windows.Forms
        $dlg = New-Object System.Windows.Forms.OpenFileDialog; $dlg.Title = $t; $dlg.Filter = $f
        if ($dlg.ShowDialog() -eq [System.Windows.Forms.DialogResult]::OK) { $dlg.FileName } else { '' }
    }
    $rs = [runspacefactory]::CreateRunspace(); $rs.ApartmentState = 'STA'; $rs.Open()
    $p = [powershell]::Create(); $p.Runspace = $rs; [void]$p.AddScript($sb.ToString()).AddArgument($title).AddArgument($filter)
    $r = $p.Invoke(); $rs.Close(); $p.Dispose(); "$($r | Select-Object -Last 1)"
}
function Cfg-Patch ($json) {
    $ErrorActionPreference='Continue'; $json | openclaw config patch --stdin *>$null
    if (Test-GatewayUp) { openclaw gateway restart *>$null }; $ErrorActionPreference='Stop'
}
function Install-Mcp {
    $spec = Ask "MCP package (e.g. @mobilenext/mobile-mcp@latest; blank=cancel)"; if (-not $spec) { return }
    $name = Ask "Register it under name" ($spec -replace '.*/','' -replace '@.*','')
    $ErrorActionPreference='Continue'
    openclaw mcp set $name ('{"command":"cmd","args":["/c","npx","-y","'+$spec+'"]}')
    if (Test-GatewayUp) { openclaw gateway restart *>$null }
    $ErrorActionPreference='Stop'; Ok "MCP '$name' registered."; Pause
}
function Install-Skill {
    $path = Pick-Folder 'Pick the skill folder (has SKILL.md) -- Cancel to type a ClawHub/git ref'
    $ErrorActionPreference='Continue'
    if ($path) { openclaw skills install $path }
    else { $r = Ask "ClawHub/git ref (blank=cancel)"; if ($r) { openclaw skills install $r } }
    if (Test-GatewayUp) { openclaw gateway restart *>$null }
    $ErrorActionPreference='Stop'; Pause
}
function Set-Token {
    $t = Ask "Telegram bot token (from @BotFather; blank=cancel)"; if (-not $t) { return }
    [IO.File]::WriteAllText("$ClawDir\.env", "TELEGRAM_BOT_TOKEN=$t`n", (New-Object Text.UTF8Encoding($false)))
    if (Test-GatewayUp) { openclaw gateway restart *>$null }; Ok "token written to ~/.openclaw/.env"; Pause
}
function Set-Thinking {
    $l = Ask "Thinking level (off/minimal/low/medium/high)" 'off'
    Cfg-Patch ('{"agents":{"defaults":{"thinkingDefault":"'+$l+'"}}}'); Ok "thinkingDefault = $l"; Pause
}
function Toggle-Memory {
    $on  = (openclaw config get agents.defaults.memorySearch.enabled 2>$null) -match 'true'
    $new = (-not $on).ToString().ToLower()
    Cfg-Patch ('{"agents":{"defaults":{"memorySearch":{"enabled":'+$new+'}}}}'); Ok "memory = $new"; Pause
}
function Menu-Configure {
    while ($true) {
        Clear-Host; Say "== CONFIGURE OPENCLAW ==" Cyan; Write-Host ""
        Line 1 "Install an MCP  (you give the package)"        (Test-OpenClaw) 'uninstall'
        Line 2 "Install a skill (folder picker / ClawHub ref)" (Test-OpenClaw) 'uninstall'
        Line 3 "Set / reset Telegram bot token"                (Test-OpenClaw) 'uninstall'
        Line 4 "Set agent thinking level"                      (Test-OpenClaw) 'uninstall'
        Line 5 "Enable / disable memory"                       (Test-OpenClaw) 'uninstall'
        Footer
        $c = Read-Choice 5
        if ($null -eq $c) { return }
        switch ($c) { '1' { Install-Mcp } '2' { Install-Skill } '3' { Set-Token } '4' { Set-Thinking } '5' { Toggle-Memory } }
    }
}

# --- APK / XAPK onto the running AVD (an operation, not a system install) ------
function Install-Apk {
    if ($UseAndroid -and -not (Test-DeviceUp)) { Warn "No booted device -- start the AVD first."; Pause; return }
    $p = Pick-File 'Select an APK / XAPK' 'Android package (*.apk;*.xapk)|*.apk;*.xapk'
    if (-not $p) { return }
    $ErrorActionPreference='Continue'
    if ($p -match '\.xapk$') {
        Say ">>> XAPK: extract splits + install-multiple..." Cyan
        $tmp = Join-Path $env:TEMP ('xapk_' + [IO.Path]::GetFileNameWithoutExtension($p))
        Remove-Item $tmp -Recurse -Force -ErrorAction SilentlyContinue
        $zip = "$tmp.zip"; Copy-Item $p $zip -Force; Expand-Archive -LiteralPath $zip -DestinationPath $tmp -Force
        $apks = (Get-ChildItem $tmp -Filter *.apk).FullName
        if ($apks) { adb -s emulator-5554 install-multiple -r @apks } else { Warn "no split APKs in the XAPK." }
    } else { Say ">>> Installing $(Split-Path $p -Leaf)..." Cyan; adb -s emulator-5554 install -r $p }
    $ErrorActionPreference='Stop'; Pause
}

function Menu-Operation {
    while ($true) {
        Clear-Host
        Say "== RUN / OPERATION ==" Cyan
        Write-Host ""
        Line  1 "Configure OpenClaw  (opens sub-menu ...)"                    (Test-OpenClaw) 'uninstall'
        Line  2 "Status"
        Line  3 "Clear all cache"                       # TODO(defer)
        Line  4 "Session Management  (opens sub-menu ...)"
        Line  5 "Approve all pending devices"           # TODO(defer): exact pairing verb
        Line  6 "List active skills and MCPs"
        Line  7 "Open Dashboard GUI"
        Line  8 "Open TUI"                              # TODO(defer)
        Line  9 "Restart OpenClaw Gateway"
        Line 10 "Service Control  (opens sub-menu ...)"
        Line 11 "Recommend best model for my VRAM (reads MODELS.md)"   # TODO
        if ($UseAndroid) { Line 12 "Install APK / XAPK onto the AVD" (Test-DeviceUp) }
        Footer
        $c = Read-Choice 12
        if ($null -eq $c) { return }
        switch ($c) {
            '1'  { Menu-Configure }
            '2'  { Show-Status }
            '3'  { Warn "Clear all cache not wired yet (see tmp-menu.md)."; Pause }
            '4'  { Menu-Sessions }
            '5'  { Warn "Approve devices not wired yet (needs the pairing verb)."; Pause }
            '6'  { List-SkillsMcps }
            '7'  { Open-Dashboard }
            '8'  { Warn "Open TUI not wired yet."; Pause }
            '9'  { Restart-Gateway }
            '10' { Menu-Service }
            '11' { Recommend-Model }
            '12' { if ($UseAndroid) { Install-Apk } }
        }
    }
}

# Run standalone -> show this menu. start_here.ps1 sets OC_Sourced to skip this.
if (-not $global:OC_Sourced) { $global:OC_Entry = $PSCommandPath; Menu-Operation }
